name: 'publish-tauri-arm64'

on:
  workflow_dispatch:

jobs:
  build-tauri-arm64:
    permissions:
      contents: write
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            dpkg \
            fakeroot \
            rpm \
            gcc-aarch64-linux-gnu

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Tauri CLI and dependencies
        run: |
          # 安装 Tauri CLI
          npm install @tauri-apps/cli
          
          # 创建或更新 package.json 脚本
          if [ ! -f "package.json" ]; then
            echo '{
              "name": "tauri-app",
              "version": "1.0.0",
              "private": true,
              "scripts": {
                "tauri": "tauri"
              },
              "devDependencies": {
                "@tauri-apps/cli": "^1.0.0"
              }
            }' > package.json
          else
            # 如果 package.json 已存在，添加 tauri 脚本
            npm pkg set scripts.tauri="tauri"
          fi

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add ARM64 target
        run: |
          rustup target add aarch64-unknown-linux-gnu

      - name: Setup cargo config for cross-compilation
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml << 'EOF' [target.aarch64-unknown-linux-gnu] linker = "aarch64-linux-gnu-gcc" EOF

      - name: Setup ARM64 architecture
        run: |
          sudo dpkg --add-architecture arm64
          echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy main restricted" | sudo tee -a /etc/apt/sources.list.d/arm64.list
          echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted" | sudo tee -a /etc/apt/sources.list.d/arm64.list
          echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy universe" | sudo tee -a /etc/apt/sources.list.d/arm64.list
          sudo apt-get update

      - name: Install ARM64 libraries
        run: |
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev:arm64 \
            libappindicator3-dev:arm64 \
            librsvg2-dev:arm64 \
            libssl-dev:arm64

      - name: Build Tauri application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_CONFIG_SYSROOT_DIR: /usr/aarch64-linux-gnu/
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: '--target aarch64-unknown-linux-gnu'
