name: 'publish-tauri-arm64'
on:
  workflow_dispatch:
jobs:
  build-tauri-arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      
      - name: Install Tauri CLI globally
        run: |
          # 全局安装 Tauri CLI
          npm install -g @tauri-apps/cli
          # 验证安装
          tauri --version
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Add ARM64 target
        run: rustup target add aarch64-unknown-linux-gnu
      
      - name: Setup cargo config
        run: |
          mkdir -p .cargo
          echo '[target.aarch64-unknown-linux-gnu]' > .cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> .cargo/config.toml
      
      - name: Setup ARM64 libraries
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev:arm64 \
            libssl-dev:arm64
      
      - name: Build Tauri application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_CONFIG_SYSROOT_DIR: /usr/aarch64-linux-gnu/
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: '--target aarch64-unknown-linux-gnu'
