name: Cross Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rust-embedded/cross@v1
        with:
          target: aarch64-unknown-linux-gnu
          command: build
          args: --release
