name: 'publish-tauri-arm64'
on:
  workflow_dispatch:
jobs:
  build-tauri-arm64:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf dpkg fakeroot rpm gcc-aarch64-linux-gnu
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      
      - name: Install Tauri CLI
        run: |
          if [ ! -f "package.json" ]; then
            echo '{"name":"tauri-app","version":"1.0.0","private":true,"scripts":{"tauri":"tauri"},"devDependencies":{"@tauri-apps/cli":"^1.0.0"}}' > package.json
          fi
          npm install
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Add ARM64 target
        run: rustup target add aarch64-unknown-linux-gnu
      
      - name: Setup cargo config
        run: |
          mkdir -p .cargo
          echo '[target.aarch64-unknown-linux-gnu]' > .cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> .cargo/config.toml
      
      - name: Setup ARM64 architecture
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev:arm64 libssl-dev:arm64
      
      - name: Build Tauri application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '--target aarch64-unknown-linux-gnu'
