name: 'Build Tauri ARM64'

on:
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            gcc-aarch64-linux-gnu

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Create package.json
        run: |
          if [ ! -f "package.json" ]; then
            echo '{"name": "tauri-app", "version": "1.0.0", "private": true}' > package.json
          fi

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add ARM64 target
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '--target aarch64-unknown-linux-gnu'
