name: 'publish-tauri-arm64'
on:
  workflow_dispatch:
jobs:
  build-tauri-arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu libwebkit2gtk-4.1-dev
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - run: rustup target add aarch64-unknown-linux-gnu
      
      - name: Build with cargo
        run: |
          cd src-tauri
          cargo build --target aarch64-unknown-linux-gnu --release
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
