name: 'publish-tauri-arm64'
on:
  workflow_dispatch:
jobs:
  build-tauri-arm64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu libwebkit2gtk-4.1-dev
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - run: rustup target add aarch64-unknown-linux-gnu
      - name: Create cargo config
        run: |
          mkdir -p .cargo
          echo '[target.aarch64-unknown-linux-gnu]' > .cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> .cargo/config.toml
      - name: Build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '--target aarch64-unknown-linux-gnu'
